excluded: # paths to ignore during linting.
  - Carthage
  - CHMeetupApp/Resources/Storyboards
  - CHMeetupApp/Sources/ViewControllers/Base/AZTabBarController.swift

identifier_name:
  min_length: 2
  max_length: 50

disabled_rules:
  - nesting
